@startuml
start

:начало;

if (добавить бытовую химию?) then (да)
  :ввод названия бытовой химии,\nколичество бытовой химии,\nобъёма продукта;
  if (объём шкафа больше суммы\nобъёмов бытовой химии?) then (да)
    :добавить бытовую химию в шкаф;
  else (нет)
    :конец;
  endif
endif

if (добавить продукт?) then (да)
  :ввод названия продукта,\nколичество продукта,\nобъёма продукта;
  if (объём холодильника больше\nсуммы объёмов продукта?) then (да)
    :добавить продукт в холодильник;
  else (нет)
    :конец;
  endif
endif

if (оплатить платежи?) then (да)
  :ввод суммы платежа;
  if (сумма платежа <= бюджет?) then (да)
    :вычесть платеж из бюджета;
    :платеж оплачен;
  else (нет)
    :недостаточно средств;
  endif
endif

:конец;
@enduml