@startuml

!define PRIMARY_KEY #orange
!define FOREIGN_KEY #lightblue

entity Storage {
  {color:PRIMARY_KEY} Storage_ID: string
  {color:FOREIGN_KEY} Tint: UUID
  Volume: int
  {color:FOREIGN_KEY} User_ID: int
}

entity "Storage_item" as StorageItem {
  {color:PRIMARY_KEY} ID: UUID
  {color:FOREIGN_KEY} ID_Storage: UUID
  {color:FOREIGN_KEY} Item_ID: UUID
}

entity Item {
  {color:PRIMARY_KEY} ID: UUID
  Name: string
  Volume: int
  Amount: int
}

entity Receipt {
  {color:PRIMARY_KEY} Receipt_ID: int
  Name: string
  Score: real
}

entity User {
  {color:PRIMARY_KEY} User_ID: UUID
  Budget: real
  Name: string
  Password: string
}

entity User_Receipt {
  {color:PRIMARY_KEY} User_Receipt_ID: int
  Status: bool
  {color:FOREIGN_KEY} Receipt_ID: int
  {color:FOREIGN_KEY} User_ID: int
}

' Define relationships
Storage ||--o{ StorageItem : contains
Item ||--o{ StorageItem : included_in
User ||--o{ Storage : owns
User ||--o{ User_Receipt : has
Receipt ||--o{ User_Receipt : referenced_in

@enduml