@startuml
start

:начало;
:ввод названия продукта,\nколичество продукта,\nобъёма продукта;

if (объём холодильника больше\nсуммы объёмов продукта?) then (да)
  :добавить продукт в холодильник;
  :успешно добавлено;
else (нет)
  :недостаточно места в холодильнике;
endif

:конец;
@enduml