@startuml
start

:начало;
:ввод названия бытовой химии,\nколичество бытовой химии,\nобъёма продукта;

if (объём шкафа больше суммы\nобъёмов бытовой химии?) then (да)
  :добавить бытовую химию в шкаф;
  :успешно добавлено;
else (нет)
  :недостаточно места в шкафу;
endif

:конец;
@enduml